title = "Heba Moh."
baseURL = "https://heba-mohamed-1998-portfolio.com"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true


[languages]
  [languages.en]
    title = "Heba Moh."
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Hi! This is my data Science Portfolio"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/datas science.jpg"
  recent_posts_number = 2

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/heba-mohamed-14101998/"


[[params.ananke_socials]]
name = "github"
url = "https://github.com/heba14101998"

[[params.ananke_socials]]
name = "credly"
url = "https://www.credly.com/users/heba-mohamed.b4704e8a"